#!/usr/bin/env python3
"""Generate examples/cross-os-probe from the extracted syscon table.

The probe is the experiment we cannot run on a Linux host: carry one fat APE to
a Mac or a Windows box and find out what actually happens when a Rust binary
holding Linux constants meets a kernel that numbers them differently.

It is self-checking. Because data/syscon-*.json holds cosmopolitan's value for
every constant on every OS, the generated probe knows what each value *should*
become on the host it finds itself running on. So it reports three columns --
what cosmo resolved at load time, what rustc baked in at compile time, and what
our extracted table predicted -- which measures the divergence and audits the
extractor at the same time.
"""
import json
import os

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OSES = ["linux", "xnu", "freebsd", "openbsd", "netbsd", "windows"]

# A representative slice rather than all 1591: the constants std actually leans
# on for file, socket, signal and memory work, chosen across the groups the
# divergence report flags worst.
PROBE = [
   "EINVAL", "ENOENT", "EAGAIN", "ENOTSUP", "EINTR", "EEXIST", "EPIPE",
   "ENOSYS", "ECONNREFUSED", "EWOULDBLOCK", "EADDRINUSE", "ENOTDIR",
   "O_CREAT", "O_TRUNC", "O_APPEND",
   "O_EXCL", "O_NONBLOCK", "O_DIRECTORY", "O_CLOEXEC",
   "MAP_PRIVATE", "MAP_ANONYMOUS", "MAP_FIXED", "PROT_READ", "PROT_WRITE",
   "SIGCHLD", "SIGPIPE", "SIGSEGV", "SIGALRM", "SIGUSR1", "SIGTERM",
   "SOCK_STREAM", "SOCK_DGRAM", "AF_INET", "AF_INET6", "AF_UNIX",
   "SOL_SOCKET", "SO_REUSEADDR", "SO_ERROR", "TCP_NODELAY",
   "F_GETFL", "F_SETFL", "F_GETFD", "F_SETFD",
   "CLOCK_MONOTONIC", "CLOCK_REALTIME", "AT_FDCWD",
]


def main():
   table = json.load(open(os.path.join(REPO, "data", "syscon-x86_64.json")))

   rows, externs = [], []
   for name in PROBE:
      e = table.get(name)
      if not e:
         print(f"  skip {name}: not in table")
         continue
      vals = ", ".join(str(e["values"].get(o, 0)) for o in OSES)
      rows.append(f'   ("{name}", &{name} as *const _, [{vals}]),')
      externs.append(f"   static {name}: c_int;")

   src = TEMPLATE.replace("//@EXTERNS@", "\n".join(externs))
   src = src.replace("//@ROWS@", "\n".join(rows))
   src = src.replace("@COUNT@", str(len(rows)))

   d = os.path.join(REPO, "examples", "cross-os-probe")
   os.makedirs(os.path.join(d, "src"), exist_ok=True)
   with open(os.path.join(d, "src", "main.rs"), "w") as f:
      f.write(src)
   with open(os.path.join(d, "Cargo.toml"), "w") as f:
      f.write(CARGO)
   print(f"wrote {d} with {len(rows)} constants")


CARGO = """[package]
name = "cross-os-probe"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cross-os-probe"
path = "src/main.rs"

[dependencies]
cosmo-compat = { path = "../../crates/cosmo-compat" }
"""

TEMPLATE = r'''//! GENERATED by tools/gen-probe.py -- do not edit by hand.
//!
//! Carry the fat APE built from this crate to a Mac or a Windows machine and
//! run it. It reports what a Rust binary compiled with Linux constants actually
//! does when cosmopolitan drops it on a different kernel.
//!
//! Three columns per constant:
//!   cosmo    what cosmopolitan resolved at load time (the host's real value)
//!   rustc    what rustc compiled in (always Linux's value, for this target)
//!   predict  what data/syscon-*.json says this host should use
//!
//! `cosmo != rustc` is a live portability bug -- every std call passing that
//! constant is now wrong. `cosmo != predict` would mean the extractor is wrong.

use std::ffi::c_int;
use std::io::Write;

// Pulls in the __xpg_strerror_r shim; without it, formatting any io::Error
// panics. `extern crate` because nothing here names a cosmo_compat item.
extern crate cosmo_compat as _;

extern "C" {
   /// Bitmask cosmopolitan fills in at startup once it knows the kernel.
   static __hostos: c_int;
//@EXTERNS@
}

const HOST_LINUX: c_int = 1;
const HOST_METAL: c_int = 2;
const HOST_WINDOWS: c_int = 4;
const HOST_XNU: c_int = 8;
const HOST_OPENBSD: c_int = 16;
const HOST_FREEBSD: c_int = 32;
const HOST_NETBSD: c_int = 64;

/// Column order must match OSES in tools/gen-probe.py.
const OS_NAMES: [&str; 6] = ["linux", "xnu", "freebsd", "openbsd", "netbsd", "windows"];

struct Row {
   name: &'static str,
   sym: *const c_int,
   vals: [i64; 6],
}

fn rows() -> Vec<Row> {
   // SAFETY: every symbol below is an `extern const int` that cosmopolitan
   // defines and initializes before main() runs.
   let raw: [(&'static str, *const c_int, [i64; 6]); @COUNT@] = unsafe { [
//@ROWS@
   ] };
   raw.into_iter().map(|(name, sym, vals)| Row { name, sym, vals }).collect()
}

fn host_index() -> (Option<usize>, String) {
   // SAFETY: plain int global, initialized by cosmo's runtime.
   let h = unsafe { __hostos };
   let mut names = Vec::new();
   let mut idx = None;
   for (bit, name, col) in [
      (HOST_LINUX, "linux", Some(0)),
      (HOST_XNU, "xnu (macOS)", Some(1)),
      (HOST_FREEBSD, "freebsd", Some(2)),
      (HOST_OPENBSD, "openbsd", Some(3)),
      (HOST_NETBSD, "netbsd", Some(4)),
      (HOST_WINDOWS, "windows", Some(5)),
      (HOST_METAL, "bare metal", None),
   ] {
      if h & bit != 0 {
         names.push(name);
         if idx.is_none() { idx = col; }
      }
   }
   let label = if names.is_empty() {
      format!("UNKNOWN (__hostos = {})", h)
   } else {
      format!("{} (__hostos = {})", names.join("+"), h)
   };
   (idx, label)
}

fn stage(n: &str, f: impl FnOnce() -> String + std::panic::UnwindSafe) {
   print!("  {:<22}", n);
   let _ = std::io::stdout().flush();
   match std::panic::catch_unwind(f) {
      Ok(s) => println!("ok    {}", s),
      Err(_) => println!("PANIC"),
   }
   let _ = std::io::stdout().flush();
}

fn main() {
   println!("=== cosmopolitan + Rust cross-OS probe ===\n");

   let (idx, label) = host_index();
   println!("cosmo detected host : {}", label);
   println!("rustc compiled for  : os={} arch={}",
            std::env::consts::OS, std::env::consts::ARCH);
   if idx != Some(0) {
      println!("\n  NOTE: rustc says \"linux\" because that is what the target spec");
      println!("        claims. It is baked in and cannot change at runtime -- that");
      println!("        mismatch is the entire portability problem in one line.");
   }
   println!();

   println!("--- constants ---");
   println!("  {:<16}{:>10}{:>10}{:>10}   {}",
            "name", "cosmo", "rustc", "predict", "verdict");

   let (mut same, mut diverged, mut unexpected) = (0, 0, 0);
   for r in rows() {
      // SAFETY: see rows(); each pointer is to a cosmo-initialized global.
      let live = unsafe { *r.sym } as i64;
      let baked = r.vals[0];                       // what rustc compiled in
      let predict = idx.map(|i| r.vals[i]);

      let verdict = match predict {
         _ if live == baked => { same += 1; "same on this OS" }
         Some(p) if live == p => { diverged += 1; "DIVERGES (as predicted)" }
         Some(_) => { unexpected += 1; "UNEXPECTED -- table disagrees" }
         None => { unexpected += 1; "diverges, host unknown" }
      };
      println!("  {:<16}{:>10}{:>10}{:>10}   {}",
               r.name, live, baked,
               predict.map(|p| p.to_string()).unwrap_or_else(|| "?".into()),
               verdict);
   }

   println!("\n  {} identical, {} diverged, {} unexpected",
            same, diverged, unexpected);
   if let Some(i) = idx {
      println!("  (host column: {})", OS_NAMES[i]);
   }

   println!("\n--- does std still work here? ---");
   stage("stdout", || "printing".into());
   stage("heap", || {
      let v: Vec<u64> = (0..1000).collect();
      format!("sum={}", v.iter().sum::<u64>())
   });
   stage("env::args", || format!("argc={}", std::env::args().count()));
   stage("time", || {
      let d = std::time::SystemTime::now()
         .duration_since(std::time::UNIX_EPOCH).unwrap();
      format!("unix={}", d.as_secs())
   });
   stage("threads", || {
      let h = std::thread::spawn(|| (1..=10u32).sum::<u32>());
      format!("sum={}", h.join().unwrap())
   });
   stage("file write+read", || {
      fn go() -> std::io::Result<String> {
         let p = std::env::temp_dir().join("cosmo-probe.txt");
         std::fs::write(&p, b"xyz")?;
         let s = std::fs::read_to_string(&p)?;
         std::fs::remove_file(&p).ok();
         Ok(format!("roundtrip={:?}", s))
      }
      go().unwrap_or_else(|e| format!("io error: {}", e))
   });
   stage("dir listing", || {
      let n = std::fs::read_dir(std::env::temp_dir())
         .map(|d| d.count()).unwrap_or(0);
      format!("{} entries in tmp", n)
   });
   stage("tcp connect", || {
      use std::net::TcpStream;
      use std::time::Duration;
      // Expected to fail with "connection refused"; what matters is *which*
      // error comes back, since that is an errno crossing the boundary.
      match TcpStream::connect_timeout(
         &"127.0.0.1:9".parse().unwrap(), Duration::from_millis(300)) {
         Ok(_) => "connected".into(),
         Err(e) => format!("err={:?} ({})", e.kind(), e),
      }
   });
   stage("panic + catch_unwind", || {
      let r = std::panic::catch_unwind(|| panic!("probe"));
      format!("caught={}", r.is_err())
   });

   println!("\ndone. please send this whole output back.");
}
'''

if __name__ == "__main__":
   main()
