//! GENERATED by tools/gen-probe.py -- do not edit by hand.
//!
//! Carry the fat APE built from this crate to a Mac or a Windows machine and
//! run it. It reports what a Rust binary compiled with Linux constants actually
//! does when cosmopolitan drops it on a different kernel.
//!
//! Three columns per constant:
//!   cosmo    what cosmopolitan resolved at load time (the host's real value)
//!   rustc    what rustc compiled in (always Linux's value, for this target)
//!   predict  what data/syscon-*.json says this host should use
//!
//! `cosmo != rustc` is a live portability bug -- every std call passing that
//! constant is now wrong. `cosmo != predict` would mean the extractor is wrong.

use std::ffi::c_int;
use std::io::Write;

// Pulls in the __xpg_strerror_r shim; without it, formatting any io::Error
// panics. `extern crate` because nothing here names a cosmo_compat item.
extern crate cosmo_compat as _;

extern "C" {
   /// Bitmask cosmopolitan fills in at startup once it knows the kernel.
   static __hostos: c_int;
   static EINVAL: c_int;
   static ENOENT: c_int;
   static EAGAIN: c_int;
   static ENOTSUP: c_int;
   static EINTR: c_int;
   static EEXIST: c_int;
   static EPIPE: c_int;
   static ENOSYS: c_int;
   static ECONNREFUSED: c_int;
   static EWOULDBLOCK: c_int;
   static EADDRINUSE: c_int;
   static ENOTDIR: c_int;
   static O_CREAT: c_int;
   static O_TRUNC: c_int;
   static O_APPEND: c_int;
   static O_EXCL: c_int;
   static O_NONBLOCK: c_int;
   static O_DIRECTORY: c_int;
   static O_CLOEXEC: c_int;
   static MAP_PRIVATE: c_int;
   static MAP_ANONYMOUS: c_int;
   static MAP_FIXED: c_int;
   static PROT_READ: c_int;
   static PROT_WRITE: c_int;
   static SIGCHLD: c_int;
   static SIGPIPE: c_int;
   static SIGSEGV: c_int;
   static SIGALRM: c_int;
   static SIGUSR1: c_int;
   static SIGTERM: c_int;
   static SOCK_STREAM: c_int;
   static SOCK_DGRAM: c_int;
   static AF_INET: c_int;
   static AF_INET6: c_int;
   static AF_UNIX: c_int;
   static SOL_SOCKET: c_int;
   static SO_REUSEADDR: c_int;
   static SO_ERROR: c_int;
   static TCP_NODELAY: c_int;
   static F_GETFL: c_int;
   static F_SETFL: c_int;
   static F_GETFD: c_int;
   static F_SETFD: c_int;
   static CLOCK_MONOTONIC: c_int;
   static CLOCK_REALTIME: c_int;
   static AT_FDCWD: c_int;
}

const HOST_LINUX: c_int = 1;
const HOST_METAL: c_int = 2;
const HOST_WINDOWS: c_int = 4;
const HOST_XNU: c_int = 8;
const HOST_OPENBSD: c_int = 16;
const HOST_FREEBSD: c_int = 32;
const HOST_NETBSD: c_int = 64;

/// Column order must match OSES in tools/gen-probe.py.
const OS_NAMES: [&str; 6] = ["linux", "xnu", "freebsd", "openbsd", "netbsd", "windows"];

struct Row {
   name: &'static str,
   sym: *const c_int,
   vals: [i64; 6],
}

fn rows() -> Vec<Row> {
   // SAFETY: every symbol below is an `extern const int` that cosmopolitan
   // defines and initializes before main() runs.
   let raw: [(&'static str, *const c_int, [i64; 6]); 46] = unsafe { [
   ("EINVAL", &EINVAL as *const _, [22, 22, 22, 22, 22, 87]),
   ("ENOENT", &ENOENT as *const _, [2, 2, 2, 2, 2, 2]),
   ("EAGAIN", &EAGAIN as *const _, [11, 35, 35, 35, 35, 10035]),
   ("ENOTSUP", &ENOTSUP as *const _, [95, 45, 45, 91, 86, 10045]),
   ("EINTR", &EINTR as *const _, [4, 4, 4, 4, 4, 10004]),
   ("EEXIST", &EEXIST as *const _, [17, 17, 17, 17, 17, 183]),
   ("EPIPE", &EPIPE as *const _, [32, 32, 32, 32, 32, 109]),
   ("ENOSYS", &ENOSYS as *const _, [38, 78, 78, 78, 78, 1]),
   ("ECONNREFUSED", &ECONNREFUSED as *const _, [111, 61, 61, 61, 61, 10061]),
   ("EWOULDBLOCK", &EWOULDBLOCK as *const _, [11, 35, 35, 35, 35, 10035]),
   ("EADDRINUSE", &EADDRINUSE as *const _, [98, 48, 48, 48, 48, 10048]),
   ("ENOTDIR", &ENOTDIR as *const _, [20, 20, 20, 20, 20, 3]),
   ("O_CREAT", &O_CREAT as *const _, [64, 512, 512, 512, 512, 64]),
   ("O_TRUNC", &O_TRUNC as *const _, [512, 1024, 1024, 1024, 1024, 512]),
   ("O_APPEND", &O_APPEND as *const _, [1024, 8, 8, 8, 8, 1024]),
   ("O_EXCL", &O_EXCL as *const _, [128, 2048, 2048, 2048, 2048, 128]),
   ("O_NONBLOCK", &O_NONBLOCK as *const _, [2048, 4, 4, 4, 4, 2048]),
   ("O_DIRECTORY", &O_DIRECTORY as *const _, [65536, 1048576, 131072, 131072, 2097152, 65536]),
   ("O_CLOEXEC", &O_CLOEXEC as *const _, [524288, 16777216, 1048576, 65536, 4194304, 524288]),
   ("MAP_PRIVATE", &MAP_PRIVATE as *const _, [2, 2, 2, 2, 2, 2]),
   ("MAP_ANONYMOUS", &MAP_ANONYMOUS as *const _, [32, 4096, 4096, 4096, 4096, 32]),
   ("MAP_FIXED", &MAP_FIXED as *const _, [16, 16, 16, 16, 16, 16]),
   ("PROT_READ", &PROT_READ as *const _, [1, 1, 1, 1, 1, 1]),
   ("PROT_WRITE", &PROT_WRITE as *const _, [2, 2, 2, 2, 2, 2]),
   ("SIGCHLD", &SIGCHLD as *const _, [17, 20, 20, 20, 20, 17]),
   ("SIGPIPE", &SIGPIPE as *const _, [13, 13, 13, 13, 13, 13]),
   ("SIGSEGV", &SIGSEGV as *const _, [11, 11, 11, 11, 11, 11]),
   ("SIGALRM", &SIGALRM as *const _, [14, 14, 14, 14, 14, 14]),
   ("SIGUSR1", &SIGUSR1 as *const _, [10, 30, 30, 30, 30, 10]),
   ("SIGTERM", &SIGTERM as *const _, [15, 15, 15, 15, 15, 15]),
   ("SOCK_STREAM", &SOCK_STREAM as *const _, [1, 1, 1, 1, 1, 1]),
   ("SOCK_DGRAM", &SOCK_DGRAM as *const _, [2, 2, 2, 2, 2, 2]),
   ("AF_INET", &AF_INET as *const _, [2, 2, 2, 2, 2, 2]),
   ("AF_INET6", &AF_INET6 as *const _, [10, 30, 28, 24, 24, 23]),
   ("AF_UNIX", &AF_UNIX as *const _, [1, 1, 1, 1, 1, 1]),
   ("SOL_SOCKET", &SOL_SOCKET as *const _, [1, 65535, 65535, 65535, 65535, 65535]),
   ("SO_REUSEADDR", &SO_REUSEADDR as *const _, [2, 4, 4, 4, 4, -5]),
   ("SO_ERROR", &SO_ERROR as *const _, [4, 4103, 4103, 4103, 4103, 4103]),
   ("TCP_NODELAY", &TCP_NODELAY as *const _, [1, 1, 1, 1, 1, 1]),
   ("F_GETFL", &F_GETFL as *const _, [3, 3, 3, 3, 3, 3]),
   ("F_SETFL", &F_SETFL as *const _, [4, 4, 4, 4, 4, 4]),
   ("F_GETFD", &F_GETFD as *const _, [1, 1, 1, 1, 1, 1]),
   ("F_SETFD", &F_SETFD as *const _, [2, 2, 2, 2, 2, 2]),
   ("CLOCK_MONOTONIC", &CLOCK_MONOTONIC as *const _, [1, 8, 5, 5, 3, 1]),
   ("CLOCK_REALTIME", &CLOCK_REALTIME as *const _, [0, 0, 0, 0, 0, 0]),
   ("AT_FDCWD", &AT_FDCWD as *const _, [-100, -2, -100, -100, -100, -100]),
   ] };
   raw.into_iter().map(|(name, sym, vals)| Row { name, sym, vals }).collect()
}

fn host_index() -> (Option<usize>, String) {
   // SAFETY: plain int global, initialized by cosmo's runtime.
   let h = unsafe { __hostos };
   let mut names = Vec::new();
   let mut idx = None;
   for (bit, name, col) in [
      (HOST_LINUX, "linux", Some(0)),
      (HOST_XNU, "xnu (macOS)", Some(1)),
      (HOST_FREEBSD, "freebsd", Some(2)),
      (HOST_OPENBSD, "openbsd", Some(3)),
      (HOST_NETBSD, "netbsd", Some(4)),
      (HOST_WINDOWS, "windows", Some(5)),
      (HOST_METAL, "bare metal", None),
   ] {
      if h & bit != 0 {
         names.push(name);
         if idx.is_none() { idx = col; }
      }
   }
   let label = if names.is_empty() {
      format!("UNKNOWN (__hostos = {})", h)
   } else {
      format!("{} (__hostos = {})", names.join("+"), h)
   };
   (idx, label)
}

fn stage(n: &str, f: impl FnOnce() -> String + std::panic::UnwindSafe) {
   print!("  {:<22}", n);
   let _ = std::io::stdout().flush();
   match std::panic::catch_unwind(f) {
      Ok(s) => println!("ok    {}", s),
      Err(_) => println!("PANIC"),
   }
   let _ = std::io::stdout().flush();
}

fn main() {
   println!("=== cosmopolitan + Rust cross-OS probe ===\n");

   let (idx, label) = host_index();
   println!("cosmo detected host : {}", label);
   println!("rustc compiled for  : os={} arch={}",
            std::env::consts::OS, std::env::consts::ARCH);
   if idx != Some(0) {
      println!("\n  NOTE: rustc says \"linux\" because that is what the target spec");
      println!("        claims. It is baked in and cannot change at runtime -- that");
      println!("        mismatch is the entire portability problem in one line.");
   }
   println!();

   println!("--- constants ---");
   println!("  {:<16}{:>10}{:>10}{:>10}   {}",
            "name", "cosmo", "rustc", "predict", "verdict");

   let (mut same, mut diverged, mut unexpected) = (0, 0, 0);
   for r in rows() {
      // SAFETY: see rows(); each pointer is to a cosmo-initialized global.
      let live = unsafe { *r.sym } as i64;
      let baked = r.vals[0];                       // what rustc compiled in
      let predict = idx.map(|i| r.vals[i]);

      let verdict = match predict {
         _ if live == baked => { same += 1; "same on this OS" }
         Some(p) if live == p => { diverged += 1; "DIVERGES (as predicted)" }
         Some(_) => { unexpected += 1; "UNEXPECTED -- table disagrees" }
         None => { unexpected += 1; "diverges, host unknown" }
      };
      println!("  {:<16}{:>10}{:>10}{:>10}   {}",
               r.name, live, baked,
               predict.map(|p| p.to_string()).unwrap_or_else(|| "?".into()),
               verdict);
   }

   println!("\n  {} identical, {} diverged, {} unexpected",
            same, diverged, unexpected);
   if let Some(i) = idx {
      println!("  (host column: {})", OS_NAMES[i]);
   }

   println!("\n--- does std still work here? ---");
   stage("stdout", || "printing".into());
   stage("heap", || {
      let v: Vec<u64> = (0..1000).collect();
      format!("sum={}", v.iter().sum::<u64>())
   });
   stage("env::args", || format!("argc={}", std::env::args().count()));
   stage("time", || {
      let d = std::time::SystemTime::now()
         .duration_since(std::time::UNIX_EPOCH).unwrap();
      format!("unix={}", d.as_secs())
   });
   stage("threads", || {
      let h = std::thread::spawn(|| (1..=10u32).sum::<u32>());
      format!("sum={}", h.join().unwrap())
   });
   stage("file write+read", || {
      fn go() -> std::io::Result<String> {
         let p = std::env::temp_dir().join("cosmo-probe.txt");
         std::fs::write(&p, b"xyz")?;
         let s = std::fs::read_to_string(&p)?;
         std::fs::remove_file(&p).ok();
         Ok(format!("roundtrip={:?}", s))
      }
      go().unwrap_or_else(|e| format!("io error: {}", e))
   });
   stage("dir listing", || {
      let n = std::fs::read_dir(std::env::temp_dir())
         .map(|d| d.count()).unwrap_or(0);
      format!("{} entries in tmp", n)
   });
   stage("tcp connect", || {
      use std::net::TcpStream;
      use std::time::Duration;
      // Expected to fail with "connection refused"; what matters is *which*
      // error comes back, since that is an errno crossing the boundary.
      match TcpStream::connect_timeout(
         &"127.0.0.1:9".parse().unwrap(), Duration::from_millis(300)) {
         Ok(_) => "connected".into(),
         Err(e) => format!("err={:?} ({})", e.kind(), e),
      }
   });
   stage("panic + catch_unwind", || {
      let r = std::panic::catch_unwind(|| panic!("probe"));
      format!("caught={}", r.is_err())
   });

   println!("\ndone. please send this whole output back.");
}
